name: hako_monorepo
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  melos: ^8.6.0

melos:
  scripts:
    analyze:
      exec: flutter analyze .
      description: Run `flutter analyze` across all packages.

    test:
      exec: flutter test --coverage
      packageFilters:
        dirExists: test
      description: Run `flutter test` across all packages.

    format:
      exec: dart format .
      description: Format Dart code across all packages.
