name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: 📂 Checkout code
       uses: actions/checkout@v4

     - name: 🚀 Cache pub deps
       uses: actions/cache@v3
       with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

     - name: 🦋 Setup Flutter
       uses: subosito/flutter-action@v2
       with:
          channel: stable

     - name: 📥 Get dependencies (packages/hako)
       working-directory: packages/hako
       run: flutter pub get

     - name: 📥 Get dependencies (packages/hako_test)
       working-directory: packages/hako_test
       run: flutter pub get

     - name: 🔍 Analyze packages
       run: |
         cd packages/hako && flutter analyze
         cd ../hako_test && flutter analyze

     - name: ✅ Run tests (packages/hako)
       working-directory: packages/hako
       run: flutter test --coverage

     - name: ✅ Run tests (packages/hako_test)
       working-directory: packages/hako_test
       run: flutter test --coverage
